### PR TITLE
transactionReceipt: parse event logs

### PR DESCRIPTION
**Pull request by emaG3m**
A good start with what `near-evm` provides. But Event names aren't being passed back yet.  Not sure this will be sufficient.

This event on Ethereum:
```
 NewZombie: {
    logIndex: 0,
    transactionIndex: 0,
    transactionHash: '0xd7466c0a2cd649056f27fb812ef0aa297cc9b52722c95cb827f953f3681279a5',
    blockHash: '0xacfeb9f6434659a0fd596839e5e036d6c19a6892dd447921a2f4f2f9b1cd0dd1',
    blockNumber: 2,
    address: '0x60AaD096578Ad0C77f70AaBB5b69C0a5aF9084A2',
    type: 'mined',
    id: 'log_4064ee0e',
    returnValues: Result {
      '0': '0',
      '1': 'Bob',
      '2': '1283836524067200',
      zombieId: '0',
      name: 'Bob',
      dna: '1283836524067200'
    },
    event: 'NewZombie',
    signature: '0x88f026aacbbecc90c18411df4b1185fd8d9be2470f1962f192bf84a27d0704b7',
    raw: {
      data: '0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000209e105f40198c000000000000000000000000000000000000000000000000000000000000000667656f7267650000000000000000000000000000000000000000000000000000',
      topics: [ '0x88f026aacbbecc90c18411df4b1185fd8d9be2470f1962f192bf84a27d0704b7']
    }
  }
}
```

turns up this event from near-evm:
```
      {
        NewZombie: {
          logIndex: 0,
          blockNumber: 1330,
          blockHash: '0xf71928d36da697e5c2927eca3bbf5b5f5a77785db42033b31cc9254166122f04',
          transactionHash: 'N8FNcEU4dCcu48qbt2WRQ19cPbLqRFfytYivjd7kQGz:test.near',
          transactionIndex: 0,
          address: '0x979F09AEa298A9d58c8BB5152c181e4E589b32A8',
          id: 'log_74144b47',
          returnValues: Result {
            '0': '0',
            '1': 'george',
            '2': '9180992409442700',
            zombieId: '0',
            name: 'george',
            dna: '9180992409442700'
          },
          event: 'NewZombie',
          signature: '0x88f026aacbbecc90c18411df4b1185fd8d9be2470f1962f192bf84a27d0704b7',
          raw: {
            data: '0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000209e105f40198c000000000000000000000000000000000000000000000000000000000000000667656f7267650000000000000000000000000000000000000000000000000000',
            topics: [Array]
          }
        }
      }
```

**Related Issue(s):** https://github.com/near/near-web3-provider/issues/3

**Closes Issue(s):** https://github.com/near/near-web3-provider/issues/3

**Nearcore Branch Info:** e9a9fc02c19ed2b97f720242bf98338639ed520c

**Unit tests completed?:** Y/N

**Relevant README/Documentation Updated?:** _#Y/N_

### CODE REVIEW

**Comment by barbaraliau** [comment]
@emaG3m are the two data objects that you mentioned above supposed to be the same things?

**Comment by emaG3m** [comment]
> @emaG3m are the two data objects that you mentioned above supposed to be the same things?

ideally. But I'm guessing there was logistical issues getting in the way. The corresponding issue (https://github.com/near/near-web3-provider/issues/3) says to return an object like so: 
```
{
    "logIndex": "0x1", // 1
    "blockNumber":"0x1b4", // 436
    "blockHash": "0x8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcfdf829c5a142f1fccd7d",
    "transactionHash":  "0xdf829c5a142f1fccd7d8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcf",
    "transactionIndex": "0x0", // 0
    "address": "0x16c5785ac562ff41e2dcfdf829c5a142f1fccd7d",
    "data":"0x0000000000000000000000000000000000000000000000000000000000000000",
    "topics": ["0x59ebeb90bc63057b6515673c3ecf9438e5058bca0f92585014eced636878c9a5"]
}
```

probably bc that's the information we have. Except I didn't have anything to form the "topics" field (@prestwich)

**Comment by prestwich** [comment]
There's more information on how logs are encoded here:
https://medium.com/mycrypto/understanding-event-logs-on-the-ethereum-blockchain-f4ae7ba50378

The `data` right now includes all the topics, etc. so needs to be decoded I think?

**Comment by emaG3m** [comment]
> There's more information on how logs are encoded here:
> https://medium.com/mycrypto/understanding-event-logs-on-the-ethereum-blockchain-f4ae7ba50378
> 
> The `data` right now includes all the topics, etc. so needs to be decoded I think?

to my knowledge, the event topics would include "NewZombie" and I don't believe we're getting anything back that informs us of the event name.

**Comment by prestwich** [comment]
> to my knowledge, the event topics would include "NewZombie" and I don't believe we're getting anything back that informs us of the event name.

Usually the web3 figures this out by consulting the zombie ABI. There is no information in the event itself that says "NewZombie".

**Comment by prestwich** [comment]
the `returnValues` field is also sugar that we don't support

**Comment by prestwich** [comment]
Oh! I just looked at the near-evm code. we're dropping topics. Let's stop doing that

**Comment by emaG3m** [comment]
> Oh! I just looked at the near-evm code. we're dropping topics. Let's stop doing that

coooool, thanks for looking into that. I can't parse throught that code so quickly

**Comment by prestwich** [comment]
See instructions on this PR:

https://github.com/near/near-evm/pull/44

**Comment by barbaraliau** [comment]
Also reference for what web3 returns: https://web3js.readthedocs.io/en/v1.2.4/web3-eth.html#getpastlogs

**Comment by emaG3m** [comment]
> Also reference for what web3 returns: https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getpastlogs

it lies

**Comment by prestwich** [comment]
when figuring out what the provider should return I usually use infura's RPC docs. Web3 docs lie and change types all around and do a bunch of post processing.

https://infura.io/docs/ethereum/json-rpc/eth-getLogs

```
{
      "address": "0x06012c8cf97bead5deae237070f9587f8e7a266d",
      "blockHash": "0x7c5a35e9cb3e8ae0e221ab470abae9d446c3a5626ce6689fc777dcffcab52c70",
      "blockNumber": "0x5c29fb",
      "data": "0x00000000000000000000000077ea137625739598666ded665953d26b3d8e374400000000000000000000000000000000000000000000000000000000000749ff00000000000000000000000000000000000000000000000000000000000a749d00000000000000000000000000000000000000000000000000000000005c2a0f",
      "logIndex": "0x57",
      "removed": false,
      "topics": [
        "0x241ea03ca20251805084d27d4440371c34a0b85ff108f6bb5611248f73818b80"
      ],
      "transactionHash": "0x788b1442414cb9c9a36dba2abe250763161a6f6395788a2e808f1b34e92beec1",
      "transactionIndex": "0x54"
    }
```

**Comment by barbaraliau** [comment]
> when figuring out what the provider should return I usually use infura's RPC docs. Web3 docs lie and change types all around and do a bunch of post processing.

That's a bunch of wtf, but also somehow that does not surprise me at all.

**Comment by emaG3m** [comment]
I'm going to cherry-pick the commit that maintains topics onto my web3_compat near-evm branch where I keep a deployable near-evm contract...then rework this PR around that.

**Comment by emaG3m** [comment]
ok @barbaraliau @prestwich updated. everything has fallen into place!

**Comment by prestwich** [comment]
LGTM. @barbaraliau ?

**Comment by barbaraliau** [comment]
Yup. Looks good. MERGE BABY MERGE.

**Pull request merged**
